#!/bin/sh

set -e

echo "Setting up database..."

db_username=${COLLE_DB_USERNAME}
db_password=${COLLE_DB_PASSWORD}
db_name=${COLLE_DB_NAME}

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOF
  CREATE USER $db_username WITH PASSWORD '$db_password';
  ALTER ROLE $db_username CREATEROLE;
  ALTER ROLE $db_username NOSUPERUSER;
  CREATE DATABASE $db_name;
  \c $db_name;
  GRANT ALL ON SCHEMA public TO $db_username;
  GRANT USAGE ON SCHEMA public TO $db_username;
  GRANT ALL PRIVILEGES ON DATABASE $db_name TO $db_username;
EOF

echo "Done."
